server:
  port: 9999

spring:
  redis:
    host: nexus-panorama.chinanorth.cloudapp.chinacloudapi.cn
    database: 2
    password: redis
  application:
    name: api-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: nexus-panorama.chinanorth.cloudapp.chinacloudapi.cn:8848
        group: PANORAMA_TEST
      config:
        server-addr: nexus-panorama.chinanorth.cloudapp.chinacloudapi.cn:8848
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
        - id: scene-service
          uri: lb://scene-service
          predicates:
            - Path=/api/v1/panoramas/**

nacos:
  gateway:
    dynamic:
      route:
        groupId: GATEWAY_TEST
        dataId: GATEWAY

jwt:
  token:
    secret: Milooi89qw901ic
    prefix: LOCAL
